# Generated by Django 5.1.7 on 2025-04-09 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='purchase',
            table='purchase',
        ),
    ]
