# Generated by Django 5.1.7 on 2025-04-07 14:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
