# Generated by Django 5.1.7 on 2025-04-08 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='Warehouse_id',
            new_name='Warehouse',
        ),
    ]
