# Generated by Django 5.1.7 on 2025-04-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_warehouse_id_inventory_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
