# Generated by Django 5.1.7 on 2025-04-09 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventory_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='Warehouse',
            new_name='warehouse',
        ),
    ]
