# Generated by Django 5.1.7 on 2025-04-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_warehouse_inventory_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='available_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='threshold',
            field=models.IntegerField(default=0),
        ),
    ]
