# Generated by Django 5.1.7 on 2025-04-09 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventory_available_qty_inventory_threshold'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inventory',
            table='inventory',
        ),
        migrations.AlterModelTable(
            name='warehouse',
            table='warehouse',
        ),
    ]
